import type { Submission } from "@/types/submission";

// Temporary in-memory seed data for admin UI scaffolding, until Firestore reads are wired up.
export const mockSubmissions: Submission[] = [
    {
        id: "VS-2026-0016",
        status: "submitted",
        submitterType: "anon",
        submissionType: "online",
        createdAt: new Date("2026-02-24T10:45:00"),
        owner: {
            name: "Margaret Wilson",
            email: "margaret.wilson@example.com",
            phone: "+61 412 345 678",
            address: "12 Blue Gum Drive, Toowoomba, QLD 4000",
            memberNumber: "DA-118874",
        },
        veterinarian: {
            veterinarianName: "Dr. James Henderson",
            practiceName: "Countryside Animal Hospital",
            address: "45 Ridge Road, Toowoomba, QLD 4000",
            phone: "(07) 5550 1234",
            positiveIdentificationSighted: true,
            certificateOfRegistrationSighted: true,
        },
        dog: {
            id: "dog-0016",
            examType: "hipsAndElbows",
            isDogsAustraliaRegistered: true,
            registeredName: "Rusty",
            registeredNumber: "ANKC-2100456789",
            microchipNumber: "900118001234567",
            breed: "Golden Retriever",
            sex: "male",
            dateOfBirth: "2023-05-14",
            dateOfRadiograph: "2025-10-22",
        },
        files: {
            dicomFiles: [
                {
                    fileName: "Pelvis_Hips_Example.dcm",
                    key: "submissions/VS-2026-0016/dicom/pelvis.dcm",
                    url: "/images/Hips example.jpg",
                    size: 14_890_000,
                    contentType: "image/jpeg",
                    uploadedAt: new Date("2026-02-24T10:40:00"),
                },
            ],
            supportingDocuments: [],
            ownerSignature: {
                fileName: "owner-signature.png",
                key: "submissions/VS-2026-0016/signatures/owner.png",
                url: "/signature-testing/1.jpg",
                size: 24_500,
                contentType: "image/png",
                uploadedAt: new Date("2026-02-24T10:42:00"),
            },
            veterinarianSignature: {
                fileName: "vet-signature.png",
                key: "submissions/VS-2026-0016/signatures/vet.png",
                url: "/signature-testing/2.jpg",
                size: 18_200,
                contentType: "image/png",
                uploadedAt: new Date("2026-02-24T10:43:00"),
            },
        },
        billing: {
            billingType: "payNow",
            amount: 95,
            paymentStatus: "paid",
            stripePaymentIntentId: "pi_mock_0016",
        },
    },
    {
        id: "VS-2025-0002",
        status: "pendingReview",
        submitterType: "anon",
        submissionType: "online",
        createdAt: new Date("2025-12-03T09:15:00"),
        owner: {
            name: "Robert Wilson",
            email: "robert.wilson@example.com",
            phone: "+61 423 456 789",
            address: "8 Fernbrook Ave, Brisbane, QLD 4000",
            memberNumber: "DA-102234",
        },
        veterinarian: {
            veterinarianName: "Dr. Priya Anand",
            practiceName: "Brisbane North Vet Clinic",
            address: "22 Kelvin Grove Rd, Brisbane, QLD 4059",
            phone: "(07) 3350 9988",
            positiveIdentificationSighted: true,
            certificateOfRegistrationSighted: false,
        },
        dog: {
            id: "dog-0002",
            examType: "hipsOnly",
            isDogsAustraliaRegistered: true,
            registeredName: "Bella",
            registeredNumber: "ANKC-2100112233",
            microchipNumber: "900118009876543",
            breed: "Golden Retriever",
            sex: "female",
            dateOfBirth: "2023-08-02",
            dateOfRadiograph: "2025-11-28",
        },
        files: {
            dicomFiles: [
                {
                    fileName: "Bella_Hips.dcm",
                    key: "submissions/VS-2025-0002/dicom/hips.dcm",
                    size: 12_340_000,
                    contentType: "application/dicom",
                    uploadedAt: new Date("2025-12-03T09:10:00"),
                },
            ],
            supportingDocuments: [
                {
                    fileName: "referral-letter.pdf",
                    key: "submissions/VS-2025-0002/docs/referral-letter.pdf",
                    size: 210_000,
                    contentType: "application/pdf",
                    uploadedAt: new Date("2025-12-03T09:12:00"),
                },
            ],
            ownerSignature: {
                fileName: "owner-signature.png",
                key: "submissions/VS-2025-0002/signatures/owner.png",
                size: 21_000,
                contentType: "image/png",
                uploadedAt: new Date("2025-12-03T09:13:00"),
            },
            veterinarianSignature: {
                fileName: "vet-signature.png",
                key: "submissions/VS-2025-0002/signatures/vet.png",
                size: 19_500,
                contentType: "image/png",
                uploadedAt: new Date("2025-12-03T09:14:00"),
            },
        },
        billing: {
            billingType: "invoice",
            amount: 95,
            paymentStatus: "invoiced",
            invoiceId: "INV-2025-0002",
            invoiceSentAt: new Date("2025-12-03T09:20:00"),
        },
    },
    {
        id: "VS-2026-0003",
        status: "archived",
        submitterType: "anon",
        submissionType: "online",
        createdAt: new Date("2026-01-11T14:05:00"),
        owner: {
            name: "Linda Thompson",
            email: "linda.thompson@example.com",
            phone: "+61 434 567 890",
            address: "3 Harbour St, Cairns, QLD 4870",
            memberNumber: "DA-109981",
        },
        veterinarian: {
            veterinarianName: "Dr. Michael Ford",
            practiceName: "Cairns Coastal Vets",
            address: "17 Esplanade, Cairns, QLD 4870",
            phone: "(07) 4030 2211",
            positiveIdentificationSighted: true,
            certificateOfRegistrationSighted: true,
        },
        dog: {
            id: "dog-0003",
            examType: "elbowsOnly",
            isDogsAustraliaRegistered: true,
            registeredName: "Rocky",
            registeredNumber: "ANKC-2100998877",
            microchipNumber: "900118002233445",
            breed: "French Bulldog",
            sex: "male",
            dateOfBirth: "2022-03-30",
            dateOfRadiograph: "2025-12-20",
        },
        files: {
            dicomFiles: [
                {
                    fileName: "Rocky_Elbows.dcm",
                    key: "submissions/VS-2026-0003/dicom/elbows.dcm",
                    url: "/images/Elbow example.jpg",
                    size: 10_120_000,
                    contentType: "image/jpeg",
                    uploadedAt: new Date("2026-01-11T14:00:00"),
                },
            ],
            supportingDocuments: [],
            ownerSignature: {
                fileName: "owner-signature.png",
                key: "submissions/VS-2026-0003/signatures/owner.png",
                url: "/signature-testing/3.jpg",
                size: 22_800,
                contentType: "image/png",
                uploadedAt: new Date("2026-01-11T14:02:00"),
            },
            veterinarianSignature: {
                fileName: "vet-signature.png",
                key: "submissions/VS-2026-0003/signatures/vet.png",
                url: "/signature-testing/4.jpg",
                size: 20_100,
                contentType: "image/png",
                uploadedAt: new Date("2026-01-11T14:03:00"),
            },
        },
        billing: {
            billingType: "payNow",
            amount: 95,
            paymentStatus: "paid",
            stripePaymentIntentId: "pi_mock_0003",
        },
    },
    {
        id: "VS-2026-0004",
        status: "submitted",
        submitterType: "anon",
        submissionType: "online",
        createdAt: new Date("2026-03-19T08:30:00"),
        owner: {
            name: "Sarah Jenkins",
            email: "sarah.jenkins@example.com",
            phone: "+61 445 678 901",
            address: "29 Wattle Cres, Toowoomba, QLD 4350",
            memberNumber: "DA-114420",
        },
        veterinarian: {
            veterinarianName: "Dr. Emily Carter",
            practiceName: "Toowoomba Vet Surgery",
            address: "5 Herries St, Toowoomba, QLD 4350",
            phone: "(07) 4638 7700",
            positiveIdentificationSighted: false,
            certificateOfRegistrationSighted: true,
        },
        dog: {
            id: "dog-0004",
            examType: "hipsAndElbows",
            isDogsAustraliaRegistered: false,
            registeredName: "Luna",
            microchipNumber: "900118005566778",
            breed: "Australian Shepherd",
            sex: "female",
            dateOfBirth: "2024-01-09",
            dateOfRadiograph: "2026-03-15",
        },
        files: {
            dicomFiles: [
                {
                    fileName: "Luna_Hips_Elbows.dcm",
                    key: "submissions/VS-2026-0004/dicom/combined.dcm",
                    size: 16_760_000,
                    contentType: "application/dicom",
                    uploadedAt: new Date("2026-03-19T08:25:00"),
                },
            ],
            supportingDocuments: [
                {
                    fileName: "microchip-registration.pdf",
                    key: "submissions/VS-2026-0004/docs/microchip-registration.pdf",
                    size: 156_000,
                    contentType: "application/pdf",
                    uploadedAt: new Date("2026-03-19T08:27:00"),
                },
            ],
            ownerSignature: {
                fileName: "owner-signature.png",
                key: "submissions/VS-2026-0004/signatures/owner.png",
                size: 19_900,
                contentType: "image/png",
                uploadedAt: new Date("2026-03-19T08:28:00"),
            },
        },
        billing: {
            billingType: "payNow",
            amount: 95,
            paymentStatus: "pending",
            stripePaymentIntentId: "pi_mock_0004",
        },
    },
    {
        id: "VS-2025-0005",
        status: "reviewing",
        submitterType: "clinic",
        submitterId: "clinic-001",
        submissionType: "pdf",
        createdAt: new Date("2025-11-02T13:00:00"),
        owner: {
            name: "Julianne Smith",
            email: "julianne.smith@example.com",
            phone: "+61 456 789 012",
            address: "14 Coral Ave, Gold Coast, QLD 4217",
            memberNumber: "DA-107765",
        },
        veterinarian: {
            veterinarianName: "Dr. Alan Brooks",
            practiceName: "Gold Coast Animal Care",
            address: "88 Surf Pde, Gold Coast, QLD 4217",
            phone: "(07) 5527 6600",
            positiveIdentificationSighted: true,
            certificateOfRegistrationSighted: true,
        },
        dog: {
            id: "dog-0005",
            examType: "hipsAndElbows",
            isDogsAustraliaRegistered: true,
            registeredName: "Max",
            registeredNumber: "ANKC-2100334455",
            microchipNumber: "900118007788990",
            breed: "Labrador Retriever",
            sex: "male",
            dateOfBirth: "2023-02-18",
            dateOfRadiograph: "2025-10-30",
        },
        files: {
            dicomFiles: [
                {
                    fileName: "Max_Hips_Elbows.dcm",
                    key: "submissions/VS-2025-0005/dicom/combined.dcm",
                    size: 15_430_000,
                    contentType: "application/dicom",
                    uploadedAt: new Date("2025-11-02T12:55:00"),
                },
            ],
            supportingDocuments: [],
            ownerSignature: {
                fileName: "owner-signature.png",
                key: "submissions/VS-2025-0005/signatures/owner.png",
                size: 20_500,
                contentType: "image/png",
                uploadedAt: new Date("2025-11-02T12:57:00"),
            },
            veterinarianSignature: {
                fileName: "vet-signature.png",
                key: "submissions/VS-2025-0005/signatures/vet.png",
                size: 18_700,
                contentType: "image/png",
                uploadedAt: new Date("2025-11-02T12:58:00"),
            },
            pdfForm: {
                fileName: "hayes-form-max.pdf",
                key: "submissions/VS-2025-0005/pdf-forms/hayes-form-max.pdf",
                size: 480_000,
                contentType: "application/pdf",
                uploadedAt: new Date("2025-11-02T12:59:00"),
            },
        },
        billing: {
            billingType: "invoice",
            amount: 95,
            paymentStatus: "overdue",
            invoiceId: "INV-2025-0005",
            invoiceSentAt: new Date("2025-11-02T13:05:00"),
        },
    },
    {
        id: "VS-2025-0006",
        status: "completed",
        submitterType: "anon",
        submissionType: "online",
        createdAt: new Date("2025-09-14T11:20:00"),
        owner: {
            name: "David Nguyen",
            email: "david.nguyen@example.com",
            phone: "+61 467 890 123",
            address: "61 Riverside Dr, Ipswich, QLD 4305",
            memberNumber: "DA-103321",
        },
        veterinarian: {
            veterinarianName: "Dr. Sarah Lim",
            practiceName: "Ipswich Vet Hospital",
            address: "9 Brisbane St, Ipswich, QLD 4305",
            phone: "(07) 3281 4400",
            positiveIdentificationSighted: true,
            certificateOfRegistrationSighted: true,
        },
        dog: {
            id: "dog-0006",
            examType: "hipsOnly",
            isDogsAustraliaRegistered: true,
            registeredName: "Zeus",
            registeredNumber: "ANKC-2100776655",
            microchipNumber: "900118003344556",
            breed: "German Shepherd",
            sex: "male",
            dateOfBirth: "2022-11-05",
            dateOfRadiograph: "2025-08-30",
        },
        files: {
            dicomFiles: [
                {
                    fileName: "Zeus_Hips.dcm",
                    key: "submissions/VS-2025-0006/dicom/hips.dcm",
                    size: 13_990_000,
                    contentType: "application/dicom",
                    uploadedAt: new Date("2025-09-14T11:15:00"),
                },
            ],
            supportingDocuments: [],
            ownerSignature: {
                fileName: "owner-signature.png",
                key: "submissions/VS-2025-0006/signatures/owner.png",
                size: 20_100,
                contentType: "image/png",
                uploadedAt: new Date("2025-09-14T11:17:00"),
            },
            veterinarianSignature: {
                fileName: "vet-signature.png",
                key: "submissions/VS-2025-0006/signatures/vet.png",
                size: 17_600,
                contentType: "image/png",
                uploadedAt: new Date("2025-09-14T11:18:00"),
            },
        },
        billing: {
            billingType: "payNow",
            amount: 95,
            paymentStatus: "paid",
            stripePaymentIntentId: "pi_mock_0006",
        },
    },
    {
        id: "VS-2025-0007",
        status: "archived",
        submitterType: "anon",
        submissionType: "online",
        createdAt: new Date("2025-07-22T16:40:00"),
        owner: {
            name: "Chloe Ramirez",
            email: "chloe.ramirez@example.com",
            phone: "+61 478 901 234",
            address: "4 Palm Grove, Sunshine Coast, QLD 4551",
            memberNumber: "DA-100987",
        },
        veterinarian: {
            veterinarianName: "Dr. Tom Baxter",
            practiceName: "Sunshine Coast Vet Group",
            address: "31 Ocean Dr, Sunshine Coast, QLD 4551",
            phone: "(07) 5443 9900",
            positiveIdentificationSighted: true,
            certificateOfRegistrationSighted: true,
        },
        dog: {
            id: "dog-0007",
            examType: "hipsAndElbows",
            isDogsAustraliaRegistered: true,
            registeredName: "Coco",
            registeredNumber: "ANKC-2100221144",
            microchipNumber: "900118008899001",
            breed: "Border Collie",
            sex: "female",
            dateOfBirth: "2021-06-12",
            dateOfRadiograph: "2025-07-01",
        },
        files: {
            dicomFiles: [
                {
                    fileName: "Coco_Hips_Elbows.dcm",
                    key: "submissions/VS-2025-0007/dicom/combined.dcm",
                    size: 14_220_000,
                    contentType: "application/dicom",
                    uploadedAt: new Date("2025-07-22T16:35:00"),
                },
            ],
            supportingDocuments: [
                {
                    fileName: "prior-scoring-report.pdf",
                    key: "submissions/VS-2025-0007/docs/prior-scoring-report.pdf",
                    size: 302_000,
                    contentType: "application/pdf",
                    uploadedAt: new Date("2025-07-22T16:37:00"),
                },
            ],
            ownerSignature: {
                fileName: "owner-signature.png",
                key: "submissions/VS-2025-0007/signatures/owner.png",
                size: 21_400,
                contentType: "image/png",
                uploadedAt: new Date("2025-07-22T16:38:00"),
            },
            veterinarianSignature: {
                fileName: "vet-signature.png",
                key: "submissions/VS-2025-0007/signatures/vet.png",
                size: 19_000,
                contentType: "image/png",
                uploadedAt: new Date("2025-07-22T16:39:00"),
            },
        },
        billing: {
            billingType: "payNow",
            amount: 95,
            paymentStatus: "paid",
            stripePaymentIntentId: "pi_mock_0007",
        },
    },
    {
        id: "VS-2026-0008",
        status: "pendingReview",
        submitterType: "anon",
        submissionType: "online",
        createdAt: new Date("2026-04-05T09:50:00"),
        owner: {
            name: "Henry Walsh",
            email: "henry.walsh@example.com",
            phone: "+61 489 012 345",
            address: "2 Hillcrest Rd, Rockhampton, QLD 4700",
            memberNumber: "DA-116543",
        },
        veterinarian: {
            veterinarianName: "Dr. Grace Kim",
            practiceName: "Rockhampton Animal Clinic",
            address: "18 Quay St, Rockhampton, QLD 4700",
            phone: "(07) 4922 3300",
            positiveIdentificationSighted: true,
            certificateOfRegistrationSighted: false,
        },
        dog: {
            id: "dog-0008",
            examType: "elbowsOnly",
            isDogsAustraliaRegistered: true,
            registeredName: "Duke",
            registeredNumber: "ANKC-2100556677",
            microchipNumber: "900118004455667",
            breed: "Rottweiler",
            sex: "male",
            dateOfBirth: "2023-10-21",
            dateOfRadiograph: "2026-03-28",
        },
        files: {
            dicomFiles: [
                {
                    fileName: "Duke_Elbows.dcm",
                    key: "submissions/VS-2026-0008/dicom/elbows.dcm",
                    size: 11_870_000,
                    contentType: "application/dicom",
                    uploadedAt: new Date("2026-04-05T09:45:00"),
                },
            ],
            supportingDocuments: [],
            ownerSignature: {
                fileName: "owner-signature.png",
                key: "submissions/VS-2026-0008/signatures/owner.png",
                size: 20_800,
                contentType: "image/png",
                uploadedAt: new Date("2026-04-05T09:47:00"),
            },
            veterinarianSignature: {
                fileName: "vet-signature.png",
                key: "submissions/VS-2026-0008/signatures/vet.png",
                size: 18_300,
                contentType: "image/png",
                uploadedAt: new Date("2026-04-05T09:48:00"),
            },
        },
        billing: {
            billingType: "invoice",
            amount: 95,
            paymentStatus: "invoiced",
            invoiceId: "INV-2026-0008",
            invoiceSentAt: new Date("2026-04-05T09:55:00"),
        },
    },
];
